### ISSUE TITLE
Menambahkan screenshot list HTML

### ISSUE THREAD

**Issue by mnindrazaka** [wrideveloper/miniclass-web#12]
Untuk mempermudah pembaca dalam memahami perbedaan ordered dan unordered list, maka bisa diberikan screenshot dari hasil tampilan list nya

file terkait : 
https://github.com/wrideveloper/miniclass-web/blob/master/dasar/html/list.md

**Comment by debbysa** [comment]
aku udah coba nambahkan screenshot. tolong di review mas @mnindrazaka

**Comment by debbysa** [comment]
#41 aku nge PR disini mas
