### ISSUE TITLE
Mengubah struktur materi pengenalan CSS berdasarkan guideline

### ISSUE THREAD

**Issue by mnindrazaka** [wrideveloper/miniclass-web#16]
Berikut struktur materi berdasarkan guideline, silahkan berikan komentar apabila ada yang perlu ditambahkan

### 1. Permasalahan
Dengan menggunakan HTML, kita bisa membuat struktur halaman website, namun untuk membuat halaman website yang baik, kita juga harus memperhatikan style dari halaman tersebut, seperti warna text, warna background, dll.  

### 2. Penjelasan Materi Sebagai Solusi
Untuk mengatur styling, bisa menggunakan CSS

### 3. Penjelasan Detail Materi
- struktur css (selector, property, value)
- beberapa cara untuk memasukkan css ke html (menggunakan tag `<style />`, eksternal css, inline css)

### 4. Contoh Kasus
Untuk contoh kasus, bisa diberikan langkah - langkah untuk membuat website sederhana yang memiliki judul dan paragraf, kemudian judul dan paragraf tersebut diberikan styling menggunakan css eksternal

file terkait :
https://github.com/wrideveloper/miniclass-web/blob/master/dasar/html/list.md

**Comment by zero0dayali** [comment]
Cekkk
