### ISSUE TITLE
Mengubah struktur materi menerima data dari URL berdasarkan guideline

### ISSUE THREAD

**Issue by mnindrazaka** [wrideveloper/miniclass-web#30]
Berikut struktur materi berdasarkan guideline, silahkan berikan komentar apabila ada yang perlu ditambahkan

### 1. Permasalahan
Sebelumnya, kita sudah bisa membuat web server yang dapat melakukan manipulasi data dengan rute sebagai berikut : 

`/contact` method GET - menampilkan semua data contact
`/contact` method POST - menambahkan data contact
`/contact` method PUT - mengubah data contact pada index 0
`/contact` method DELETE - menghapus seluruh data contact pada index 0

Namun, data dan index yang diinputkan selalu statis (index 0 dan data yang diinputkan selalu sama). Bagaimana cara client memberitahu server index mana  yang akan diubah / dihapus, dan data apa yang harus dibuat ?

### 2. Penjelasan Materi Sebagai Solusi
Pada web server, client dapat mengirimkan data melalui URL. Data tersebut dapat diterima dan diolah oleh server. Pada express kita dapat membaca data yang dikirim tersebut menggunakan `req.query` dan `req.params`

### 3. Penjelasan Detail Materi
- penjelasan URL query
   - struktur URL
   - cara parsing menggunakan `req.query`
- penjelasan URL params
   - struktur URL
   - cara parsing menggunakan `req.params`

### 4. Contoh Kasus
Diberikan langkah - langkah untuk menerapkan URL query dan URL params pada web server yang sudah dibuat sebelumnya. Agar index dan data yang diinputkan bisa dinamis

source code akhir contoh kasus (pastikan berikan langkah - langkah saat menjelaskan) :
```javascript
const express = require('express')
const app = express()

const contacts = [
  {
    name: "amir",
    phone: "085482938471"
  },
  {
    name: "budi",
    phone: "086452738493"
  }
]

// menampilkan semua kontak
app.get("/contact", function (req, res) {
  res.send(contacts)
})

// menambahkan kontak baru
app.post("/contact", function (req, res) {
  contacts.push({ name: req.query.name, phone: req.query.phone })
  res.send({ success: true })
})

// mengubah kontak pada index yang diinginkan
app.put("/contact", function (req, res) {
  if (contacts[req.query.index] !== undefined) {
    contacts[req.query.index] = { name: req.query.name, phone: req.query.phone }
    res.send({ success: true })
  } else {
    res.send({ success: false })
  }
})

// menghapus kontak pada index yang diinginkan
app.delete("/contact", function (req, res) {
  if (contacts[req.query.index] !== undefined) {
    contacts.splice(req.query.index, 1)
    res.send({ success: true })
  } else {
    res.send({ success: false })
  }
})

app.listen(3000, function () {
  console.log("server running")
})
```

file terkait : 
https://github.com/wrideveloper/miniclass-web/blob/master/dasar/express-js/handle-data-url.md

**Comment by daffaputradamar** [comment]
mas @mnindrazaka untuk contoh kasus nanti kita seolah2 udh nylesein materi yang sebelumnya atau dari awal lagi?
