### ISSUE TITLE
Mengubah struktur materi middleware express berdasarkan guideline

### ISSUE THREAD

**Issue by mnindrazaka** [wrideveloper/miniclass-web#31]
Berikut struktur materi berdasarkan guideline, silahkan berikan komentar apabila ada yang perlu ditambahkan

### 1. Permasalahan
Pada web server yang sudah dibuat sebelumnya, kita sudah dapat menginputkan index dan data yang akan dimanipulasi dari client. Namun server belum melakukan validasi apakah data yang dikirim client sudah lengkap atau belum.

Harusnya hal tersebut dapat dilakukan dengan memberikan kondisi (if) pada setiap rute. Namun hal ini akan membuat source code kita banyak, karena akan ada source code untuk melakukan validasi input di setiap rute.

### 2. Penjelasan Materi Sebagai Solusi
Middleware merupakan suatu fungsi yang dapat dijalankan sebelum request sampai ke rute tujuan (atau bisa disebut endpoint). Dimana fungsi tersebut bisa dimanfaatkan untuk melakukan apapun. Misalnya autentikasi, logging, atau pada kasus yang kita butuhkan adalah validasi input dari client. Selain itu, fungsi middleware dapat kita tulis sekali saja dan dapat diterapkan pada beberapa atau seluruh rute yang kita punya.

### 3. Penjelasan Detail Materi
- Cara membuat fungsi middleware pada express
- Cara menerapkan middleware pada express
   - application level middleware
   
```javascript
   const express = requitre('express')
   const app = express()

   function validateInput(req, res, next) {
      // validation logic
      next()
   }

  // used as application level middleware
  app.use(validateInput)

  app.get("/", function (req, res) {
    res.send("hello world")
  })

  app.get("/", function (req, res) {
    res.send("hello world 2")
  })
```
  - router level middleware
```javascript
   const express = requitre('express')
   const app = express()

   function validateInput(req, res, next) {
      // validation logic
      next()
   }

  // used as router level middleware
  app.get("/", validateInput, function (req, res) {
    res.send("hello world")
  })

  app.get("/", function (req, res) {
    res.send("hello world 2")
  })
```

source code akhir contoh kasus (pastikan berikan langkah - langkah saat menjelaskan) :
### 4. Contoh Kasus
Diberikan contoh untuk menerapkan middleware validasi data pada web server yang sudah dibuat sebelumnya.

```javascript
const express = require('express')
const app = express()

const contacts = [
  {
    name: "amir",
    phone: "085482938471"
  },
  {
    name: "budi",
    phone: "086452738493"
  }
]

function validateIndex(req, res, next) {
  if (req.query.index !== undefined && contacts[req.query.index] === undefined) {
    res.send({ success: false })
  } else {
    next()
  }
}

// menggunakan middleware validate index pada level aplikasi
app.use(validateIndex)

app.get("/contact", function (req, res) {
  res.send(contacts)
})

app.post("/contact", function (req, res) {
  contacts.push({ name: req.query.name, phone: req.query.phone })
  res.send({ success: true })
})

// middleware validate index bisa juga digunakan pada rute tertentu :
app.put("/contact", validateIndex, function (req, res) {
  contacts[req.query.index] = { name: req.query.name, phone: req.query.phone }
  res.send({ success: true })
})

// middleware validate index bisa juga digunakan pada rute tertentu :
app.delete("/contact", validateIndex, function (req, res) {
  contacts.splice(req.query.index, 1)
  res.send({ success: true })
})

app.listen(3000, function () {
  console.log("server running")
})
```

file terkait : 
https://github.com/wrideveloper/miniclass-web/blob/master/dasar/express-js/middleware.md

**Comment by ardananjungkusuma** [comment]
#72
