### ISSUE TITLE
Mengubah struktur materi menyimpan data ke database berdasarkan guideline

### ISSUE THREAD

**Issue by mnindrazaka** [wrideveloper/miniclass-web#33]
Berikut struktur materi berdasarkan guideline, silahkan berikan komentar apabila ada yang perlu ditambahkan

### 1. Permasalahan
Sebelumnya, kita sudah bisa membuat web server yang dapat melakukan manipulasi data, dan menerima data dari body. Namun data tersebut hanya disimpan ke variable. Masalahnya, apabila server direstart, maka data yang disimpan pada variable tersebut akan hilang, karena variable disimpan pada memory sementara (RAM).

### 2. Penjelasan Materi Sebagai Solusi
Agar data yang disimpan permanen, dan tidak hilang saat server direstart, maka data tersebut harus disimpan ke dalam suatu file. File disini bisa berupa file text, atau pada kasus ini lebih cocok menggunakan database seperti MySQL.   

### 3. Penjelasan Detail Materi
- cara install package mysql
- cara melakukan koneksi dari express ke mysql
- cara menjalankan query mysql pada express

### 4. Contoh Kasus
Diberikan langkah - langkah untuk melakukan CRUD ke database menggunakan express dan MySQL

file terkait : 
https://github.com/wrideveloper/miniclass-web/blob/master/dasar/express-js/node-mysql.md

**Comment by gopla** [comment]
mas, struktur tabelnya gimana?
Aku buat bebas?
