### ISSUE TITLE
Mengubah struktur materi list HTML berdasarkan guideline

### ISSUE THREAD

**Issue by mnindrazaka** [wrideveloper/miniclass-web#45]
Berikut struktur materi berdasarkan guideline, silahkan berikan komentar apabila ada yang perlu ditambahkan

### 1. Permasalahan
Pada pembuatan website, biasanya kita butuh menampilkan data dalam bentuk list untuk mempermudah pembacaan. Namun, pada HTML kita tidak bisa langsung membuat list menggunakan text, karena enter tidak terbaca di HTML.

### 2. Penjelasan Materi Sebagai Solusi
Untuk membuat list di HTML, bisa menggunakan kombinasi dari tag `<ol />`, `<ul />`, dan `<li />`

### 3. Penjelasan Detail Materi
Dijelaskan langkah - langkah untuk membuat ordered list dan unordered list

### 4. Contoh Kasus
Untuk contoh kasus, bisa diberikan langkah - langkah untuk membuat sebuah halaman web yang menampilkan data dalam bentuk list. Misalnya menampilkan makanan favorit, daftar pekerjaan yang harus dikerjakan, dll.

file terkait :
https://github.com/wrideveloper/miniclass-web/blob/master/dasar/html/list.md

**Comment by naufalyukafi** [comment]
mas aka saya masih bingung dengan permasalahannya, itu tetep sesuai yang di atas atau di ganti?

**Comment by naufalyukafi** [comment]
thanks mas
