### ISSUE TITLE
Mengubah struktur materi mengunggah file berdasarkan guideline

### ISSUE THREAD

**Issue by mnindrazaka** [wrideveloper/miniclass-web#61]
Berikut struktur materi berdasarkan guideline, silahkan berikan komentar apabila ada yang perlu ditambahkan

### 1. Permasalahan
Terkadang, sebuah web server harus dapat menerima file dari client. Misalnya apabila kita akan membuat sebuah web yang memiliki fitur upload seperti upload foto profile.

### 2. Penjelasan Materi Sebagai Solusi
Untuk mengirim sebuah file, client harus mengirimkan data melalui body dengan format `form data`. Kemudian server dapat memparsingnya menggunakan middleware `multer`

### 3. Penjelasan Detail Materi
- penjelasan form data
  - cara mengirim form data dari frontend javascript
  - cara parsing form data ke req.files menggunakan middleware `multer`

### 4. Contoh Kasus
Diberikan langkah - langkah untuk membuat web server yang dapat mengupload file

source code akhir contoh kasus (pastikan berikan langkah - langkah saat menjelaskan) :
```javascript
const express = require('express')
const app = express()
const multer = require('multer')

// menentukan lokasi pengunggahan
const upload = multer({ dest: 'public/upload/' })

const contacts = [
  {
    name: "amir",
    phone: "085482938471"
  },
  {
    name: "budi",
    phone: "086452738493"
  }
]

function validateIndex(req, res, next) {
  if (req.query.index !== undefined && contacts[req.query.index] === undefined) {
    res.send({ success: false })
  } else {
    next()
  }
}

app.use(validateIndex)
app.use(express.json())

app.get("/contact", function (req, res) {
  res.send(contacts)
})

app.post("/contact", function (req, res) {
  contacts.push({ name: req.body.name, phone: req.body.phone })
  res.send({ success: true })
})

app.put("/contact", function (req, res) {
  contacts[req.query.index] = { name: req.body.name, phone: req.body.phone }
  res.send({ success: true })
})

app.delete("/contact", function (req, res) {
  contacts.splice(req.query.index, 1)
  res.send({ success: true })
})

// menerapkan middleware multer hanya pada rute berikut
app.put("/contact/upload", upload.single('photo'), function (req, res) {
  // menyimpan lokasi penggungahan pada data contacts pada index yang diinginkan
  contacts[req.query.index].photo = req.file.path
  res.send({ success: true })
})

app.listen(3000, function () {
  console.log("server running")
})
```

**Comment by debbysa** [comment]
itu kenapa ada validateIndex juga mas?

**Comment by debbysa** [comment]
Ini aku kasih contoh upload file yang lebih sederhana (tanpa menggunakan array) boleh kan mas?
Soalnya kalo kayak contoh diatas menurutku kepanjangan, nanti takut bingung memahaminya, sama takut ada yang berasumsi kalo bikin upload multer harus bikin array dulu.

dari aku itu sih concern nya. menurut smean gimana?

**Comment by mnindrazaka** [comment]
> itu kenapa ada validateIndex juga mas?

nyambung sama contoh kasus di materi2 sebelumnya

**Comment by mnindrazaka** [comment]
> Ini aku kasih contoh upload file yang lebih sederhana (tanpa menggunakan array) boleh kan mas?
> Soalnya kalo kayak contoh diatas menurutku kepanjangan, nanti takut bingung memahaminya, sama takut ada yang berasumsi kalo bikin upload multer harus bikin array dulu.
> 
> dari aku itu sih concern nya. menurut smean gimana?

iya bener, makanya di detail materi itu dikasih tau cara upload file pake multer yang paling sederhana (gak perlu array dll).

tapi untuk implementasi di contoh kasus, tetep ngikut dari contoh kasus - contoh kasus sebelumnya.

**Comment by debbysa** [comment]
#88

**Comment by debbysa** [comment]
pull req materi upload file
#88
